questboard-app/config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  get 'errors/internal_server_error'

  root 'quests#index'
  get '/login' => 'sessions#login', as: :login
  post '/login'   => 'sessions#create' , as: :login_user
  get '/signup' => 'sessions#register', as: :register
  post '/signup' => 'sessions#register_user', as: :register_user
  get '/logout'  => 'sessions#destroy', as: :logout_user
  get '/send_verify' => 'sessions#send_verify'
  get '/verify_email' => 'sessions#verify_email'
  get '/forgot_password' => 'sessions#reset_password', as: :reset_password
  post '/forgot_password' => 'sessions#forgot_password', as: :forgot_password
  get '/reset_password' => 'sessions#send_password', as: :send_password

  get '/' => 'quests#index', as: :quests

  get '/quests/new' => 'quests#new', as: :new_quest
  get '/quests/pending_quests' => 'quests#pending_quests', as: :pending_quests
  get '/quests/general_quests' => 'quests#general_quests', as: :general_quests
  get '/quests/my_quests' => 'quests#my_quests', as: :my_quests
  get '/quests/assigned_quests' => 'quests#assigned_quests', as: :assigned_quests
  get '/quests/:id' => 'quests#show', as: :quest
  get '/quests/edit/:id' => 'quests#edit', as: :edit_quest
  post '/quests/accept/:id' => 'quests#accept', as: :accept_quest
  post '/quests/reject/:id' => 'quests#reject', as: :reject_quest
  post '/quests/edit/:id' => 'quests#update', as: :update_quest
  post '/quests/new' => 'quests#create', as: :create_quest
  delete '/quests/:id'=> 'quests#destroy', as: :delete_quest

  
  get '/quests/review/:id' => 'quests#review', as: :review_quest
  post '/quests/review/:id' => 'quests#add_review', as: :add_review_quest
  resources :comments

  get '/notifications' => 'notifications#index', as: :notifications
  post '/notifications' => 'notifications#seen'

  
  get '/users/:id' => 'users#show', as: :user
  get '/users/edit/:id' => 'users#edit', as: :edit_user
  post '/users/edit/:id' => 'users#update', as: :user_update

  get '/quests/task/:id' => 'task#index', as: :task
  get '/quests/task/add/:id' => 'task#create', as: :create_task
  post '/quests/task/add/:id' => 'task#create_task', as: :add_task
  delete '/quests/task/:id' => 'task#destroy', as: :delete_task
  
  get '/quests/:id/:string' => 'quests#status', as: :status_quest
  resources :users

  get 'auth/:provider/callback' => 'sessions#google_create', as: :google_signin
  get '/disconnect_google' => 'sessions#google_delete', as: :google_delete
  get 'auth/failure', to: redirect('/')
  
  %w( 404 500 errorX ).each do |code|
  get code, :to => "errors#show", :code => code
end

  

end

questboard-app/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "sample app", root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li>
					<%= link_to "Home", root_path %>
				</li>
				<li>
					<%= link_to "Help", help_path %>
				</li>

				<% if logged_in? %>
				<li>
					<%= link_to "Users", '#' %>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b> </a>
					<ul class="dropdown-menu">
						<li>
							<%= link_to "Profile", current_user %>
						</li>
						<li>
							<%= link_to "Settings", '#' %>
						</li>
						<li class="divider"></li>
						<li>
							<%= link_to "Log out", logout_path, method: "delete" %>
						</li>
					</ul>
				</li>
				<% else %>
				<li>
					<%= link_to "Log in", login_path %>
				</li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

questboard-app/app/views/layouts/_new_quest.html.erb
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" >
  <div class="modal-dialog" style="left: 0em">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&#215;</button>
        <h2 class="modal-title">Create a new Quest</h4>
      </div>
      <div class="modal-body">
        <%= form_for :quest, :url => create_quest_path, :remote => true, html: { multipart: true } do |f| %>
          <table class="table table-hover table-striped table-content" style="width:80%;border-collapse: separate;border-spacing: 0em 1em;" >
            <tr >
              <td><h4>  Title: </h4> </td>
              <td ><%= f.text_field :title, placeholder: "Enter quest title", class: "input", style: "width:100%", :validate => true %></td>
              <!-- <td></td> -->
            </tr>
            <tr >
              <td> <h4> Description:  </h4> </td>
              <td><%= f.text_area :description, placeholder: "Enter quest description", class: "textarea", style: "width:100%", :validate => true %></td>
              <!-- <td></td> -->
            </tr>
            <tr>
              <td> <h4>Due date: </h4></td>
              <td><%= f.date_select :due_date, :order => [:day, :month, :year] %></td> <td></td>
            </tr>
            <tr>
              <td> <h4>Add images: </h4> </td>
              <td><%= file_field_tag "photos[]", type: :file, multiple: true %></td> <td></td>
            </tr>
            <tr>
              <td> <h4> Add Youtube Videos: </h4> </td>
              <td style="width:80%;"><%= f.text_field :url, placeholder: "Video url", class: "input", style: "width:100%" %></td>
            </tr>
            <tr>
              <td><h4 >Reminder: </h4></td>
              <td><%= f.datetime_select :reminder,:ampm => true, :minute_step => 1, :order => [:day, :month, :year] %></td>
              <td><%= f.check_box :remind_to %></td>
              <!-- <td><%#= f.check_box :default_reminder %></td> -->
              <!-- <td><input type="checkbox" checked data-toggle="toggle" data-onstyle="info"></td>  -->
              <!-- <td><input type="checkbox" checked data-toggle="toggle" data-onstyle="info"></td>  -->
            </tr>
            <tr>
              <td>
              <button class="btn btn-default" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample" style="background-color: gray; color:white;">Assign Someone</button>
              </td>
              <!-- <td></td><td></td> -->
            </tr>
            <tr>
              <table class="collapse table table-hover table-striped table-content" id="collapseExample"  style="width:80%;border-collapse: separate;border-spacing: 0em 1em;">
                <tr>
                  <td><h4> Assign to: </h4></td> 
                  <td ><%= f.text_field :assign_to, placeholder: "Who do you want to assign the Quest to?", class: "input", style: "width:100%" ,:validate => true %></td>
                </tr>  
                <tr>
                  <td><h4> Bounty: </h4> </td>  
                  <td ><%= f.text_field :bounty, placeholder: "Bounty", class: "input", style: "width:50%" %></td>
                  <td><%= f.select :bounty_points, [['10',10],['20',20],['30',30], ['40',40], ['50',50], ['60',60], ['70',70], ['80',80], ['90',90], ['100',100]]%></td>
                </tr>
              </table>
            </tr>
          </table>
          <!-- <div class="modal-footer"> -->
          <!-- <tr> -->
            <td></td><td colspan="1"><%= f.submit "Create", class: "button btn btn-primary btn-lg btn-block", remote: true %></td>
            <td>
              <input id="toggle-one" checked type="checkbox">
              <script>
                $(function() {
                  $('#toggle-one').bootstrapToggle();
                })
              </script>
            </td>
          <!-- </tr> -->
          <!-- </div> -->
        <% end %>
      </div>
    </div><!-- < /.modal-content -->
  </div><!-- < /.modal-dialog  -->
</div><!-- /.modal -->

questboard-app/app/views/layouts/_sidebar.html.erb
<div class="container">
  <ul id="gn-menu" class="gn-menu-main">
    <li class="gn-trigger">
      <a class="gn-icon gn-icon-menu"><span>Menu</span></a>
      <nav class="gn-menu-wrapper">
        <div class="gn-scroller">
          <ul class="gn-menu">
            <li class="gn-search-item">
              <li><%= form_tag(users_path, :method => "get", id: "search-form") do %>
                  <%= text_field_tag :search, params[:search], placeholder: "Search Users", class:"gn-search"%>
                  <a class="gn-icon gn-icon-search"><span>Search</span></a><br>
                  <%= submit_tag "Search", :name => nil, :style => "display:none" %>
                <% end %>
              </li>
            </li>
            <a class="gn-icon" href="/quests/my_quests"><div class="side-elem"><li style="margin-left: 3.5em">My Quests</li></div></a>
            <a class="gn-icon" href="/quests/general_quests"><div class="side-elem"><li style="margin-left: 3.5em">General Quests</li></div></a>
            <a class="gn-icon" href="/quests/pending_quests"><div class="side-elem"><li style="margin-left: 3.5em">Pending Quests</li></div></a>
            <a class="gn-icon" href="/quests/assigned_quests"><div class="side-elem"><li style="margin-left: 3.5em">Assigned Quests</li></div></a>

            <!-- <li><a class="gn-icon gn-icon-download" href="/quests/my_quests">My Quests</a></li>
            <li><a class="gn-icon gn-icon-cog" href="/quests/general_quests">General Quests</a></li>
            <li><a class="gn-icon gn-icon-help" href="/quests/pending_quests">Pending Quest</a></li>
            <li><a class="gn-icon gn-icon-help" href="/quests/assigned_quests">Assigned Quest</a></li> -->
          </ul>
        </div>
      </nav>
    </li>
  </ul>
</div>
<script>
  new gnMenu( document.getElementById( 'gn-menu' ) );
</script>

questboard-app/app/views/layouts/application.html.erb
<html>
  <head>
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.0/css/bootstrap-toggle.min.css" rel="stylesheet">
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.0/js/bootstrap-toggle.min.js"></script>
    <script src="https://apis.google.com/js/client:platform.js" async defer></script>
    <title>QuestBoard</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="https://d26b395fwzu5fz.cloudfront.net/3.2.4/keen.min.js" type="text/javascript"></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400' rel='stylesheet' type='text/css'>

    <meta charset="utf-8">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content=""> -->
    <!-- <head> -->
    <!-- <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Neu v1.4  |  Responsive Admin Skin</title> -->

     <!-- Bootstrap core CSS -->
     <link href="/dist/css/bootstrap.css" rel="stylesheet"/> 
    
    <!-- Boostrap Theme -->
    <link id="skinCss" href="/css/theme-base.css" rel="stylesheet"/>
    <!-- <link href="/css/boostrap-overrides.css" rel="stylesheet"/>  -->
    <link id="themeCss" href="/css/theme.css" rel="stylesheet"/>

    <!-- Add custom CSS here -->
    <link href="/assets/css/sidebar.css" rel="stylesheet"/>
    
    <link rel="stylesheet" href="/assets/ShinyButtonCss/normalize.css">
    <link rel="stylesheet" href="/assets/ShinyButtonCss/style.css">  

    <!-- // <script src="ShinyButtonjs/modernizr.js"></script> -->
    <!-- Plugins -->
    <!-- <link rel="shortcut icon" href="../favicon.ico"> -->
    <!-- <link rel="stylesheet" type="text/css" href="NavCss/normalizeNav.css" /> -->
    <!--      <link rel="stylesheet" type="text/css" href="/assets/NavCss/demoNav.css" />  -->
    <link rel="stylesheet" type="text/css" href="/assets/NavCss/componentNav.css" /> 
    <!-- // <script src="/assets/modernizr.custom.js"></script> -->

       <!--  -->
    <!-- </head> -->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <!-- IN-APP NOTIFICATIONS -->
    <script>
      var client;
      <% if logged_in? %>
          $( window ).load(function() {
            client = initFayeClient();
            subscribeForNotifications('/notifs/<%= @current_user.id %>');
          });
      <% else %>
        quitClient(client);
      <% end %>
    </script>
    <!-- /IN-APP NOTIFICATIONS -->
    <% exemptions = ['/login', '/signup', '/forgot_password']%>
    <% if not exemptions.include? request.path %>
      <!-- Top Navbar  -->
      <div class="navbar navbar-static-top navbar-default" role="navigation" style="position: fixed; width:100%; top: 0em"> 
        <div class="navbar-header navbar text-center">
          <!-- SIDEBAR -->
          <%= render :partial => '/layouts/sidebar' %>
          <!-- /SIDEBAR -->
          <!-- LOGO -->
          <div class="navbar-brand" style="margin-left : 50px; margin-top: 0px;" style="background-color:grey;">
            <a class="app-logo" href="/"><h2 style="margin-top: 0.2em;">QuestBoard</h2></a>
          </div>
          <!-- /LOGO -->
        </div>
                <!-- user -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav navbar-right navbar-user">
            <li><%#= link_to "Find Users", users_path %></li>
            <!-- NEW QUEST -->
            <%= render :partial => '/layouts/new_quest' %>
            <!-- /NEW QUEST -->
            <!-- NOTIFICATIONS -->
            <li class="dropdown">
              <a href="/notifications" class="announcements" style="margin: -7px;">
                <i class="glyphicon glyphicon-flag"></i>
                <span class="badge animated-delay flash">
                  <% unread = User.unread_notifications_count @current_user %>
                  <%=  unread %>
                </span>
              </a>
              <!-- <ul class="dropdown-menu">
                <li class="dropdown-header header-inverse"><i class="icon-star"></i>Notifications </li>
                <li class="divider"></li>
                <li class="dropdown-footer text-center">
                    <a href="/notifications">
                        See all notifications
                    </a>
                </li>
              </ul> -->
            </li>
            <!-- /NOTIFICATIONS -->
            <!-- USER -->
            <li class="avatar dropdown user-dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><h4>Welcome <%= @current_user.first_name%>!<b class="caret"></b></h4></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", user_path(@current_user.id), class: "navbar-link" %></li>
                  <li><%= link_to "Edit Profile", edit_user_path(current_user), method: :get ,class:"navbar-link"%></li>
                  <li><a href="/logout"><i class="icon-power-off"></i> Log Out</a></li>
                </ul>
            </li>
            <!-- /USER -->
          </ul>
        </div><!--  / nav-collapse -->
      </div>       
      <!-- <button class="shiny-button"  data-toggle="modal" data-target="#myModal2" style="margin-top: 15px;margin-left : 90%;" >New Quest</button> -->
    <% end %>
    <%#= yield %>
    <div class="container-body">
      <div class="container-container" style="padding: 01em;background-color: transparent;">
        <% if not exemptions.include? request.path %>
          <button class="shiny-button"  data-toggle="modal" data-target="#myModal2" style="margin-top: 10%;margin-left : 90%;" >New Quest</button>
          <br>
          <% end %>
        <%= yield %>
      </div>
    </div>

    <!-- NOTIFICATIONS BOX -->
    <div class="notifs display-none">
      <p class="notifs-message"></p>
    </div>
    <!-- /NOTIFICATIONS BOX -->

    <script>
      $.noConflict();
      // $(window).ready(function(){
      //     $('input[name="commit"]').click(function(){
      //         if($("#quest_title").val() == ""){
      //             alert("Please write Title");
      //         }
      //         if($("#quest_description").val() == ""){
      //             alert("Please write Descripton");
      //         }
      //     });
      // });
    </script>
  </body>
</html>

questboard-app/app/views/layouts/new.html.erb
<% provide(:title, 'Log in') %> <h1>Log in p</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(:session , :url => login_user_path ) do |f| %>

		<%= f.label :email %>
		<%= f.email_field :email %>

		<%= f.label :password %>
		<%= f.password_field :password %>

		<%= f.submit "Log in", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

questboard-app/app/views/layouts/s.erb
<!DOCTYPE html>
<html>
  <head>

   
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <script>
      var client;
      <% if logged_in? %>
          $( window ).load(function() {
            client = initFayeClient();
            subscribeForNotifications('/notifs/<%= @current_user.id %>');
          });
      <% else %>
        quitClient(client);
      <% end %>
    </script>
  <% if (request.path != "/login" && request.path != "/signup") %>
    <div class="header">
      <div style="float: left;width: 40%;height: 55%;position:relative;left:5em;border: 0px solid rgba(208, 208, 208, 0.67);position: relative;top:25%;">     
        <%= link_to "QuestBoard", root_path, class: "logo", style: "float: left; color: white" %>
      </div>
      <div style="float:right;height: 100%;right: 15em;position:relative">
        <ul class="navbar-links">
          <li style="float: left">

            <button class="btn btn-default dropdown-toggle" type="button" id="menu1" data-toggle="dropdown" style="margin-right: 0.3em">Boards<span class="caret"></span></button>
            <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
              <li role="presentation"><a role="menuitem" tabindex="-1" href="<%= root_path %>">My Quests</a></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="<%= general_quests_path %>">General Quests</a></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="<%= pending_quests_path %>">Pending Quests</a></li>
            </ul>
          </li>
          <li style="float: left">
            <% unread = User.unread_notifications_count @current_user %>
            <% notifs = "Notifications" %>
            <% if unread > 0 %>
            <% notifs += " [#{unread}]" %>
            <% end %>
            <%= link_to "#{notifs}", notifications_path, class: "navbar-link notifs-label" %>
          </li>
          <li style="float: left">
            <%= link_to @current_user.first_name, user_path(@current_user.id), class: "navbar-link" %>
          </li>
          <li style="float: left">
            <%= link_to "Log out", logout_user_path, class: "navbar-link" %>
          </li>
        </ul>
      </div>
    </div>
  <% end %>

    <%#= yield %>
    <div class="container-body">
      <div class="container-container" style="padding: 01em;background-color: transparent;">
        <%= yield %>
      </div>
    </div>

    <div class="notifs display-none">
      <p class="notifs-message"></p>
    </div>


  </body>
</html>