questboard-app/config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  get 'errors/internal_server_error'

  root 'quests#index'
  get '/login' => 'sessions#login', as: :login
  post '/login'   => 'sessions#create' , as: :login_user
  get '/signup' => 'sessions#register', as: :register
  post '/signup' => 'sessions#register_user', as: :register_user
  get '/logout'  => 'sessions#destroy', as: :logout_user
  get '/send_verify' => 'sessions#send_verify'
  get '/verify_email' => 'sessions#verify_email'
  get '/forgot_password' => 'sessions#reset_password', as: :reset_password
  post '/forgot_password' => 'sessions#forgot_password', as: :forgot_password
  get '/reset_password' => 'sessions#send_password', as: :send_password

  get '/' => 'quests#index', as: :quests

  get '/quests/new' => 'quests#new', as: :new_quest
  get '/quests/pending_quests' => 'quests#pending_quests', as: :pending_quests
  get '/quests/general_quests' => 'quests#general_quests', as: :general_quests
  get '/quests/my_quests' => 'quests#my_quests', as: :my_quests
  get '/quests/assigned_quests' => 'quests#assigned_quests', as: :assigned_quests
  get '/quests/:id' => 'quests#show', as: :quest
  get '/quests/edit/:id' => 'quests#edit', as: :edit_quest
  post '/quests/accept/:id' => 'quests#accept', as: :accept_quest
  post '/quests/reject/:id' => 'quests#reject', as: :reject_quest
  post '/quests/edit/:id' => 'quests#update', as: :update_quest
  post '/quests/new' => 'quests#create', as: :create_quest
  delete '/quests/:id'=> 'quests#destroy', as: :delete_quest

  
  get '/quests/review/:id' => 'quests#review', as: :review_quest
  post '/quests/review/:id' => 'quests#add_review', as: :add_review_quest
  resources :comments

  get '/notifications' => 'notifications#index', as: :notifications
  post '/notifications' => 'notifications#seen'

  
  get '/users/:id' => 'users#show', as: :user
  get '/users/edit/:id' => 'users#edit', as: :edit_user
  post '/users/edit/:id' => 'users#update', as: :user_update

  get '/quests/task/:id' => 'task#index', as: :task
  get '/quests/task/add/:id' => 'task#create', as: :create_task
  post '/quests/task/add/:id' => 'task#create_task', as: :add_task
  delete '/quests/task/:id' => 'task#destroy', as: :delete_task
  
  get '/quests/:id/:string' => 'quests#status', as: :status_quest
  resources :users

  get 'auth/:provider/callback' => 'sessions#google_create', as: :google_signin
  get '/disconnect_google' => 'sessions#google_delete', as: :google_delete
  get 'auth/failure', to: redirect('/')
  
  %w( 404 500 errorX ).each do |code|
  get code, :to => "errors#show", :code => code
end

  

end

questboard-app/app/models/task.rb
class Task <ActiveRecord::Base
	belongs_to :quest, foreign_key: "quest_id"
	belongs_to :user, foreign_key: "user_id"

end

questboard-app/app/controllers/task_controller.rb
class TaskController < ApplicationController
	def index
		@quest = Quest.find(params[:id])
		@tasks = @quest.tasks
	end

	#creates a new task view
	def create
	end

	#creates a new task and redirects to the quest
	def create_task
	@task = Task.create(:quest_id => params[:id], :user_id => @current_user.id, :title => params[:task][:title])
	redirect_to quest_path(params[:id])
	end

	#deletes a task
	def destroy
		Task.destroy(params[:id])
		redirect_to quest_path(params[:id])
		
	end
end

questboard-app/app/helpers/task_helper.rb
module TaskHelper
end

questboard-app/app/views/task/create.html.erb
<div>
	<%= form_for :task, :url => add_task_path(params[:id]), html: { multipart: true } do |f| %>
		<table style="width:80%;border-collapse: separate;border-spacing: 0em 1em;">
			<tr style="padding-bottom: 1em">
				<td><font class="label" style="width:20%;">Task: </font></td>
				<td style="width:80%;"><%= f.text_field :title, placeholder: "Enter quest title", class: "input", style: "width:100%" %></td>
			</tr>

			<tr><td></td><td colspan="1"><%= f.submit "Create", class: "login-button", class: "button", style: "float: right" %></td></tr>
		</table>
	<% end %>
</div>

questboard-app/app/views/task/index.html.erb
<%= link_to "+", create_task_path(params[:id]), class: "circular-button", style: "float: right; color: white;" %>
<div>
	<table style="width:80%;border-collapse: separate;border-spacing: 0em 1em;margin-left: 4em;">
		<% @tasks.each do |task| %>

   <tr style="padding-bottom: 1em">
    <td><%= link_to "#{task.title}", task_path(task.id), class: "label", style: "margin-bottom: 0.5em;" %></td>
    <%if task.user == @current_user.id%>
    <td style=""><%= button_to "X", delete_task_path(task.id), method: :delete, class: "button", style: "width: 20%;float:right;" %></p></td>
    <%end%>
  </tr>
  <% end %>
</table>

</div>