questboard-app/config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  get 'errors/internal_server_error'

  root 'quests#index'
  get '/login' => 'sessions#login', as: :login
  post '/login'   => 'sessions#create' , as: :login_user
  get '/signup' => 'sessions#register', as: :register
  post '/signup' => 'sessions#register_user', as: :register_user
  get '/logout'  => 'sessions#destroy', as: :logout_user
  get '/send_verify' => 'sessions#send_verify'
  get '/verify_email' => 'sessions#verify_email'
  get '/forgot_password' => 'sessions#reset_password', as: :reset_password
  post '/forgot_password' => 'sessions#forgot_password', as: :forgot_password
  get '/reset_password' => 'sessions#send_password', as: :send_password

  get '/' => 'quests#index', as: :quests

  get '/quests/new' => 'quests#new', as: :new_quest
  get '/quests/pending_quests' => 'quests#pending_quests', as: :pending_quests
  get '/quests/general_quests' => 'quests#general_quests', as: :general_quests
  get '/quests/my_quests' => 'quests#my_quests', as: :my_quests
  get '/quests/assigned_quests' => 'quests#assigned_quests', as: :assigned_quests
  get '/quests/:id' => 'quests#show', as: :quest
  get '/quests/edit/:id' => 'quests#edit', as: :edit_quest
  post '/quests/accept/:id' => 'quests#accept', as: :accept_quest
  post '/quests/reject/:id' => 'quests#reject', as: :reject_quest
  post '/quests/edit/:id' => 'quests#update', as: :update_quest
  post '/quests/new' => 'quests#create', as: :create_quest
  delete '/quests/:id'=> 'quests#destroy', as: :delete_quest

  
  get '/quests/review/:id' => 'quests#review', as: :review_quest
  post '/quests/review/:id' => 'quests#add_review', as: :add_review_quest
  resources :comments

  get '/notifications' => 'notifications#index', as: :notifications
  post '/notifications' => 'notifications#seen'

  
  get '/users/:id' => 'users#show', as: :user
  get '/users/edit/:id' => 'users#edit', as: :edit_user
  post '/users/edit/:id' => 'users#update', as: :user_update

  get '/quests/task/:id' => 'task#index', as: :task
  get '/quests/task/add/:id' => 'task#create', as: :create_task
  post '/quests/task/add/:id' => 'task#create_task', as: :add_task
  delete '/quests/task/:id' => 'task#destroy', as: :delete_task
  
  get '/quests/:id/:string' => 'quests#status', as: :status_quest
  resources :users

  get 'auth/:provider/callback' => 'sessions#google_create', as: :google_signin
  get '/disconnect_google' => 'sessions#google_delete', as: :google_delete
  get 'auth/failure', to: redirect('/')
  
  %w( 404 500 errorX ).each do |code|
  get code, :to => "errors#show", :code => code
end

  

end

questboard-app/app/controllers/quests_controller.rb
class QuestsController < ApplicationController
skip_before_filter  :verify_authenticity_token

  def index
    quests = UsersQuest.where(:assignor_id => @current_user.id, :assignee_id => @current_user.id).pluck(:quest_id)
    @quests = Quest.where(:id => quests).order('due_date')
  end

  def my_quests
     quests = UsersQuest.where(:assignor_id => @current_user.id, :assignee_id => @current_user.id).pluck(:quest_id)
    @quests = Quest.where(:id => quests).order('due_date')
  end

  def new
  end

  def edit
    @Quest = Quest.find(params[:id])
  end

  #destroy the specified quest and all of its dependencies
  def destroy
    @Uquest = UsersQuest.find_by_quest_id(params[:id])
    if(@Uquest.assignor_id == @current_user.id)
      quest = Quest.find_by_id(params[:id])
      if not quest.gid.blank?
        Quest.delete_calendar_event quest, @current_user
      end
      UsersQuest.delete_all(:quest_id => params[:id])
      Quest.delete_all(:id => params[:id])
      Task.delete_all(:quest_id => params[:id])
      Reminder.delete_all(:quest_id => params[:id])
    end
    redirect_to :back
  end

  #get all quests which arent accepted yet
  def index
    # TODO: Find personal quests
    quests = UsersQuest.where(:assignor_id => @current_user.id).pluck(:quest_id)
    @quests = Quest.where(:id => quests).order('due_date')
  end

  # returns all the quests that are assigned by the user and to the users which are yet to be accepted
  def pending_quests
    quests = UsersQuest.where(:assignee_id => @current_user.id,:is_accepted => false,:is_rejected =>false).pluck(:quest_id)
    @quests = Quest.where(:id => quests).order('due_date')
    by_me_quests = UsersQuest.where(:assignor_id => @current_user.id,:is_accepted => false,:is_rejected =>false).pluck(:quest_id)
    @by_me_quests = Quest.where(:id => by_me_quests).order('due_date')
  end


  #get all quests which are accepted
  def general_quests
    quests = UsersQuest.where(:assignee_id => @current_user.id,:is_accepted => true).where.not(:assignor_id => @current_user.id).pluck(:quest_id)
    @quests = Quest.where(:id => quests).order('due_date')
  end

  def assigned_quests
    quests = UsersQuest.where(:assignor_id => @current_user.id,:is_accepted => true).where.not(:assignee_id => @current_user.id).pluck(:quest_id)
    @quests = Quest.where(:id => quests).order('due_date')
  end

  #Shows all information about a Quest.
  def show
    @user_quest = UsersQuest.find(params[:id])
    @assignor_id = @user_quest.assignor_id
    @assignee_id = @user_quest.assignee_id
    @is_accepted = @user_quest.is_accepted
    @is_rejected = @user_quest.is_rejected
    @name = User.find(@user_quest.assignee_id)
    @Quest = Quest.find(@user_quest)
    @photos = @Quest.quest_images
    if QuestVideo.find_by_quest_id(@Quest.id).url != ""
      @video = QuestVideo.find_by_quest_id(@Quest.id).url.split('/').last
    else
      @video = ""
    end
    @tasks = @Quest.tasks
    @comments = @Quest.comments.all
    @comment = @Quest.comments.build
  end

  #Shows the Review related to certain Quest.
  def review
    @user_quest = UsersQuest.find(params[:id])
  end

  #Gives the User the option to write a review on a certain Quest.
  def add_review
    UsersQuest.update(params[:id], params.require(:quest).permit(:review))
    quest = Quest.find(params[:id])

    if params[:quest][:points] == "1"
      quest.bounty_points += 10
      quest.save
    end
    if params[:quest][:points] == "2"
      quest.bounty_points += 20
      quest.save
    end
    if params[:quest][:points] == "3"
      quest.bounty_points += 30
      quest.save
    end
    if params[:quest][:points] == "4"
      quest.bounty_points += 40
      quest.save
    end
    if params[:quest][:points] == "5"
      quest.bounty_points += 50
      quest.save
    end
    redirect_to quest_path(quest.id)
  end

# accepts the assigned quest, notifies the assignor, and increases the connection frequency
  def accept
    respond_to do |format|
      user_quest = UsersQuest.update(params[:id], :is_accepted => true, :is_rejected => false)
      @assignor_id = Connection.find_by("user_id = ? OR connection_id = ?", user_quest.assignor_id, user_quest.assignee_id)
      if @assignor_id == nil
        @assignor_id = Connection.create(:user_id => user_quest.assignor_id, :connection_id => user_quest.assignee_id)
      end
      @assignor_id.frequency += 1
      @assignor_id.save
      notif_user = User.find_by(:id => user_quest.assignor_id)
      notif = Notification.create(:user_id => user_quest.assignor_id,
        :title => "#{@current_user.first_name} #{@current_user.last_name} has accepted your assigned quest: #{Quest.find(params[:id]).title}",
        :url => quest_path(user_quest.quest_id))
      @options = {:channel => "/notifs/#{user_quest.assignor_id}",
                  :message => notif.title,
                  :count => "#{User.unread_notifications_count notif_user}", :redirect => quest_path(params[:id]),
                  :url => quest_path(user_quest.quest_id),
                  :id => notif.id}
      format.html {redirect_to quest_path(params[:id])}
      format.js
    end
  end

# rejects the assigned quest and notifies the assignor
  def reject
    respond_to do |format|
      user_quest = UsersQuest.update(params[:id],:is_accepted => false,:is_rejected => true)
      notif_user = User.find_by(:id => user_quest.assignor_id)
      notif = Notification.create(:user_id => user_quest.assignor_id,
        :title => "#{@current_user.first_name} #{@current_user.last_name} has rejected your assigned quest: #{Quest.find(params[:id]).title}",
        :url => quest_path(user_quest.quest_id))
      @options = {:channel => "/notifs/#{user_quest.assignor_id}",
                  :message => notif.title,
                  :count => "#{User.unread_notifications_count notif_user}", :redirect => quest_path(params[:id]),
                  :url => quest_path(user_quest.quest_id),
                  :id => notif.id}
      format.html {redirect_to quest_path(params[:id])}
      format.js
    end
  end

  #Gives the User the option to write a review on a certain Quest.
  def add_review
    UsersQuest.update(params[:id], params.require(:quest).permit(:review))
    redirect_to quest_path(params[:id])
  end

  #A User can create the Quest with a title, description, deadline, bounty and assign the Quest to another User.
  def create
    hash = params.require(:quest).permit(:title, :description, :due_date, :bounty)
    hash[:assign_to] = params[:quest][:assign_to]
    hash[:remind_to] = params[:quest][:remind_to]
    # hash[:default_reminder] = params[:quest][:default_reminder]
    respond_to do |format|
      if not params[:quest][:assign_to].blank?
        if params[:quest][:assign_to] =~ /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
          user = User.find_by(:email => params[:quest][:assign_to])
          if user == nil
            if params[:quest][:assign_to] =~ /^\S+@gmail.com$/
              non_user = true
            else
              flash[:notice] = 'No assinee with this email'
              format.html {redirect_to create_quest_path and return}
              @options = {:redirect => create_quest_path}
              format.js
              return
            end
          end
        else
          user = User.find_by(:username => params[:quest][:assign_to])
          if  user == nil
            flash[:notice] = 'No assinee with this username'
            # redirect_to create_quest_path and return
            format.html {redirect_to create_quest_path and return}
            @options = {:redirect => create_quest_path}
            format.js
            return
          end
        end
      end
      @quest = Quest.create_general_quest(hash, @current_user, params.require(:quest).permit(:reminder, :remind_to))
      Quest.assign_non_user @current_user, @quest, params[:quest][:assign_to] if non_user == true
      if params[:photos]

        params[:photos].each { |photo|
          @quest.quest_images.create(:photo => photo)
        }
      end
      @quest.quest_videos.create(:url => params[:quest][:url])
      if not hash[:assign_to].blank?
        user_quest = UsersQuest.find_by(:quest_id => @quest.id)
        notif_user = User.find_by(:id => user_quest.assignee_id)
        if notif_user == nil
          format.html {redirect_to quest_path(@quest.id)}
          @options = {:redirect => quest_path(@quest.id)}
          format.js
          return
        end
        notif = Notification.create(:user_id => user_quest.assignee_id,
                                    :title => "#{@current_user.first_name} #{@current_user.last_name} has assigned you a quest: #{@quest.title}",
                                    :url => quest_path(@quest.id))
        @options = {:channel => "/notifs/#{user_quest.assignee_id}",
                    :message => notif.title,
                    :count => "#{User.unread_notifications_count notif_user}", :redirect => quest_path(@quest.id),
                    :url => quest_path(@quest.id),
                    :id => notif.id}

        format.html {redirect_to quest_path(@quest.id)}
        format.js
      else
        @options = {:redirect => quest_path(@quest.id)}
        format.html {redirect_to quest_path(@quest.id)}
        format.js
      end
    end
  end

# update the content of the specified quest
  def update
    hash = params[:quest]
    # flash[:warning] = []
    # flash[:warning] << "Title cannot be left blank" if hash[:title].blank?
    # redirect_to edit_quest_path and return if flash[:warning].count > 0
    Quest.update(params[:id], params.require(:quest).permit(:title, :description, :due_date,:bounty, :assign_to))
    quest = Quest.find_by_id(params[:id])
    if not quest.gid.blank?
      Quest.update_calendar_event quest, @current_user
    end
    redirect_to quest_path(params[:id])
  end

# Updates the quest's current status and tracks the number of quests each gender completes
  def status

questboard-app/app/views/quests/accept.js.erb
publishNotification('<%= @options[:channel] %>', {
  message : '<%= @options[:message] %>',
  count: '<%= @options[:count] %>',
  url: '<%= @options[:url] %>',
  id: '<%= @options[:id] %>'
}, '<%= @options[:redirect] %>');

questboard-app/app/views/quests/review.html.erb

<%= form_for :quest, :url => review_quest_path(params[:id]) do |f| %>

<font class="label">Review: </font>
				<%= f.text_area :review, placeholder: "Enter Review about the person", class: "textarea", style: "width:100%;resize: vertical;" %>
				<div class="btn-toolbar" role="toolbar" aria-label="...">
				<%= f.radio_button :points, 1 %>
        <font style="margin-right: 0.5em">1</font>
        <%= f.radio_button :points, 2 %>
        <font style="margin-right: 0.5em">2</font>
         <%= f.radio_button :points, 3 %>
        <font style="margin-right: 0.5em">3</font>
         <%= f.radio_button :points, 4 %>
        <font style="margin-right: 0.5em">4</font>
         <%= f.radio_button :points, 5 %>
        <font style="margin-right: 0.5em">5</font>

        <div><%= button_to "Submit", add_review_quest_path(params[:id]), method: :post, class: "button", style: "width: 20%;float:right;" %></div>
				
			
				
<!-- <button type="button" class="btn btn-default">1</button>
<button type="button" class="btn btn-primary">2</button>
<button type="button" class="btn btn-success">3</button>
<button type="button" class="btn btn-info">4</button>
<button type="button" class="btn btn-warning">5</button> -->
</div>
<% end %>

questboard-app/app/views/quests/show.html.erb

<!-- Project Accordions -->
<!-- Accordion 1 -->
<div class="row col-sm-12">
 <div class="panel-group" id="accordionrnd_1">
   <!-- Accordion header -->
   <div class="panel top no-icon">
     <div class="panel-heading">
      <div class="row col-md-12">

       <div class="col-xs-6">
         <h4><%=@Quest.title%></h4>
         <div class="col-xs-6">
          <div class="progress progress-striped active">
            <div class="progress-bar progress-bar-gray"  role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width:0%" id="pro-bar"></div>
          </div> 
        </div>
      </div>
      <div class="tools pull-right text-transparent">
        <a href="#"><i class="icon-refresh"></i></a>
        <a href="#"><i class="icon-trash"></i></a>
        <a href="#"><i class="icon-star"></i></a>
      </div>
    </div>
    <div class="clearfix"></div>
  </div>
</div><!-- / Accordion header -->
<!-- / project description -->
<div class="panel">
  <div class="panel-heading task-list">
    <a data-toggle="collapse" data-parent="#accordionrnd_1" href="#project1b">
     <i class="icon-pencil text-transparent"></i>
     &nbsp;&nbsp;Description
   </a>
 </div>
 <div id="project1b" class="accord-collapse panel-collapse collapse">
  <div class="panel-body">
   <%= @Quest.description%>
 </div>
</div>
</div><!-- / project description -->
<!-- notes -->
<div class="panel">
  <div class="panel-heading brand-highlight task-list">
    <a data-toggle="collapse" data-parent="#accordionrnd_1" href="#project1c">
     <i class="icon-file-alt text-transparent"></i>
     &nbsp;&nbsp;Details&nbsp;&nbsp;&nbsp;&nbsp;
   </a>
 </div>
 <div id="project1c" class="accord-collapse panel-collapse collapse">
  <div class="panel-body">
    <%= @Quest.bounty%>
  </br>
  Due Date: <%= @Quest.due_date.strftime("%d-%m-%Y")%>
</br>
<% if @assignor_id != @assignee_id %>
Assigned to: <%="#{@name.first_name} #{@name.last_name}"%>
</br>
<% end %>
<%if @Quest.is_completed%>
  Completed at: <%= @Quest.completed_at.strftime("%d-%m-%Y %H:%M") %>
<%end%>
</div>
</div>
</div><!-- notes -->
<!-- bottom panel -->

<div class="panel">
  <div class="panel-heading task-list">
    <a data-toggle="collapse" data-parent="#accordionrnd_1" href="#project1d">
     <i class="icon-file-alt text-transparent"></i>
     &nbsp;&nbsp;Media&nbsp;&nbsp;&nbsp;&nbsp;
   </a>
 </div>
 <div id="project1d" class="accord-collapse panel-collapse collapse">
  <div class="panel-body">
    <%if QuestVideo.find_by_quest_id(@Quest.id).url != ""%>
    <iframe width="560" height="349" src="<%= "http://www.youtube.com/embed/"+@video %>"></iframe>
  </p>
  <%end%>
  <td><font  style="width:20%;">Images </font></td>
  <% @photos.each do |pic| %>
    <%= link_to image_tag(pic.photo.url (:small)), pic.photo.url %>
  <%end%>
</div>
</div>
</div>

<div class="panel">
  <div class="panel-heading brand-highlight task-list">
    <a data-toggle="collapse" data-parent="#accordionrnd_1" href="#project1f">
     <i class="icon-file-alt text-transparent"></i>
     &nbsp;&nbsp;Tasks&nbsp;&nbsp;&nbsp;&nbsp;
   </a>
 </div>
 <div id="project1f" class="accord-collapse panel-collapse collapse">
  <div class="panel-body">
    <% @tasks.each do |task| %>
    <tr style="padding-bottom: 1em">
        <td><font  style="width:20%;">- <%=task.title%></font></td>
        </p>
        <%if task.user == @current_user%>
        <td style=""><%= button_to "Delete", delete_task_path(task.id), class: "btn btn-default", method: :delete %></p></td>
        <%end%>
    </tr>
    <%end%>
    <tr>
    <%if not @Quest.status == "Done"%>
       <button class="btn btn-default" type="button" data-toggle="collapse" data-target="#collapseExample2" aria-expanded="false" aria-controls="collapseExample" style="background-color: gray; color:white;">
            Add Task
            </button>
    <%end%>
    </td>
    <div class="collapse" id="collapseExample2" style="padding-bottom: 1em">
    <%= form_for :task, :url => add_task_path(params[:id]), html: { multipart: true } do |f| %>
        <table style="width:80%;border-collapse: separate;border-spacing: 0em 1em;">
            <tr style="padding-bottom: 1em">
                <td><font  style="width:20%;">Task: </font></td>
                <td style="width:80%;"><%= f.text_field :title, placeholder: "Enter Task",id: '5'%></td>
            </tr>

            <tr><td></td><td colspan="1"><%= f.submit "Add", name: 'lol' %></td></tr>
        </table>
    <% end %>
    </div>
</div>
</div>


<div class="panel bottom">
  <div class="panel-heading task-list">
    <a data-toggle="collapse" data-parent="#accordionrnd_1" href="#project1e">
     <i class="icon-user text-transparent"></i>
     &nbsp;&nbsp;Options
   </a>
 </div>


   <div id="project1e" class="accord-collapse panel-collapse collapse">
  <%= button_to "Edit Quest", edit_quest_path(@Quest.id), method: :get, class: "button", style: "margin-top: 0.5em;" %>

  <% if @current_user.id == @assignee_id and @current_user.id != @assignor_id and @is_accepted == false and @is_rejected == false%>

    <%= button_to "Accept", accept_quest_path(@Quest.id), method: :post, remote: true, class: "button", style: "margin-top: 0.5em;" %>


    <%= button_to "Reject", reject_quest_path(@Quest.id), method: :post, remote: true, class: "button", style: "margin-top: 0.5em;" %>

  <%end%>
  <% if @Quest.is_completed == true && @current_user.id == @assignor_id && @current_user.id != @assignee_id%>
  <button class="btn btn-default" type="button" data-toggle="collapse" data-target="#collapseExample3" aria-expanded="false" aria-controls="collapseExample" style="background-color: gray; color:white;">
            Add Review
            </button>
             <div class="collapse" id="collapseExample3" style="padding-bottom: 1em">
    <%= form_for :quest, :url => review_quest_path(params[:id]) do |f| %>

<font >Review: </font>
        <%= f.text_area :review, placeholder: "Enter Review about the person" %>
        
        <%= f.radio_button :points, 1 %>
        <font >1</font>
        <%= f.radio_button :points, 2 %>
        <font >2</font>
         <%= f.radio_button :points, 3 %>
        <font>3</font>
         <%= f.radio_button :points, 4 %>
        <font >4</font>
         <%= f.radio_button :points, 5 %>
        <font >5</font>

        <div><%= button_to "Submit", add_review_quest_path(params[:id]), method: :post %></div>
        
      
        
<!-- <button type="button" class="btn btn-default">1</button>
<button type="button" class="btn btn-primary">2</button>
<button type="button" class="btn btn-success">3</button>
<button type="button" class="btn btn-info">4</button>
<button type="button" class="btn btn-warning">5</button> -->

<% end %>

    </div>
  
  <%end%>
  <br>
  <div class="btn-group" role="group" aria-label="...">
    

    <%if @user_quest.is_accepted==true and @assignee_id == @current_user.id %>
    <button type="submit" class="btn btn-default" onclick="window.location.href='/quests/<%= @Quest.id%>/OnIt'" id = "1">
      On it
    </button>
    <button type="button" class="btn btn-default" onclick="window.location.href='/quests/<%= @Quest.id%>/InProgress'" id = "2">
      in Progress
    </button>
    <button type="button" class="btn btn-default" onclick="window.location.href='/quests/<%= @Quest.id%>/Done'" id = "3" remote="true">
      Done
    </button>
    <%end%>
</div>
</div>
</div>
<div class="panel">
  <div class="panel-heading brand-highlight task-list">
    <a data-toggle="collapse" data-parent="#accordionrnd_1" href="#project1g">
     <i class="icon-file-alt text-transparent"></i>
     &nbsp;&nbsp;Comments&nbsp;&nbsp;&nbsp;&nbsp;
   </a>
 </div>
 <div id="project1g" class="accord-collapse panel-collapse collapse">
  <div class="panel-body">
    <h3>Comments</h3>
<% @comments.each do |comment| %>
  <div>
    <strong><%= comment.user_name %></strong>
    <br />
    <p><%= comment.body %></p>
    <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
  </div>
<% end %>
<%= render 'comments/form' %>
</div>
</div>
</div>

</table>
</div>

<!--<h3>Comments</h3>
<% @comments.each do |comment| %>
  <div>
    <strong><%= comment.user_name %></strong>
    <br />
    <p><%= comment.body %></p>
    <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
  </div>
<% end %>
<%= render 'comments/form' %>-->


<script><%if @Quest.status == "OnIt" %>



  $("#1").prop("disabled",true);
            //  document.getElementById("1").disabled=true;
            $("#pro-bar").css("width", "33%");

            <% elsif @Quest.status == "InProgress"%>

            document.getElementById("2").disabled=true;
            $("#pro-bar").css("width", "66%");

            <% elsif @Quest.status == "Done"%>

            document.getElementById("3").disabled=true;
            document.getElementById("2").disabled=true;
            document.getElementById("1").disabled=true;
            $("#pro-bar").css("width", "100%");

            <%end%>

          </script>
          <!-- /bottom  panel -->

        </div>
      </div>
<!--     <tr style="padding-bottom: 1em">

        <td style="width:80%;" ><h1><%= @Quest.title%></h1></td>
    </p>

    <td><font  style="width:20%;">Description: </font></td>
    <td style="width:80%;"><font ><%= @Quest.description%></font></td>
</p>
</p>
<td><font  style="width:20%;">Bounty: </font></td>
<td style="width:80%;"><%= @Quest.bounty%></td>
</p>
<td><font  style="width:20%;">Due date: </font></td>
<td style="width:80%;"><%= @Quest.due_date%></td>
</p>
<%if @Quest.is_completed%>
<td><font  style="width:20%;">Completed at: </font></td>
<td style="width:80%;"><%= @Quest.completed_at%></td>
<%end%>
</p>

<td><font  style="width:20%;">Assgined to:</font></td>
<font  style="width:20%;"><%=@name.username%></font>
</p>
<%if @user_quest.is_accepted==true%>
<td><font size="2" class="label label-info">Accepted</font></td>
<%end%>
<%if @user_quest.is_rejected==true%>
<td><font size="2" class="label label-info">Rejected</font></td>
<%end%>
<%if @user_quest.is_accepted==false and @user_quest.is_rejected==false%>
<td><font size="2" class="label label-info">Pending</font></td>
<%end%>
</p>
<div class="progress">
  <div id = "pro-bar" class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
  </div>
</div>
    <td>
    <%if not @Quest.status == "Done"%>
       <button class="btn btn-default" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample" style="background-color: gray; color:white;">
            Add Task
            </button>
    <%end%>
    </td>
    <div class="collapse" id="collapseExample" style="padding-bottom: 1em">
    <%= form_for :task, :url => add_task_path(params[:id]), html: { multipart: true } do |f| %>
        <table style="width:80%;border-collapse: separate;border-spacing: 0em 1em;">
            <tr style="padding-bottom: 1em">
                <td><font  style="width:20%;">Task: </font></td>
                <td style="width:80%;"><%= f.text_field :title, placeholder: "Enter quest title", class: "input", style: "width:100%" %></td>
            </tr>

            <tr><td></td><td colspan="1"><%= f.submit "Add", class: "login-button", class: "button", style: "float: right" %></td></tr>
        </table>
    <% end %>
</div>
    <br>
    <% @tasks.each do |task| %>
    <tr style="padding-bottom: 1em">
        <td><font  style="width:20%;">-<%= task.title%></font></td>
        </p>
        <%if task.user == @current_user.id%>
        <td style=""><%= button_to "X", delete_task_path(task.id), method: :delete, class: "button", style: "width: 20%;float:right;" %></p></td>
        <%end%>
    </tr>
    <% end %>
<br>

<%if QuestVideo.find_by_quest_id(@Quest.id).url != ""%>
<iframe width="560" height="349" src="<%= "http://www.youtube.com/embed/"+@video %>"></iframe>
</p>
<td><font  style="width:20%;">Images </font></td>
<%end%>
<% @photos.each do |pic| %>
<%= link_to image_tag(pic.photo.url (:small)), pic.photo.url %>
<% end %>
<div class="btn-group" role="group" aria-label="...">
    
        <%if @user_quest.is_accepted==true%>
        <button type="submit" class="btn btn-default" onclick="window.location.href='/quests/<%= @Quest.id%>/OnIt'" id = "1">
            On it
        </button>
        <button type="button" class="btn btn-default" onclick="window.location.href='/quests/<%= @Quest.id%>/InProgress'" id = "2">
            in Progress
        </button>
        <button type="button" class="btn btn-default" onclick="window.location.href='/quests/<%= @Quest.id%>/Done'" id = "3">
            Done
        </button>
    </div>
    <%end%>
</p>
<%if @Quest.is_completed%>
<td><font  style="width:20%;">Completed at: </font></td>
<td style="width:80%;"><%= @Quest.completed_at%></td>
<%end%>
</p>

</tr>
-->



